//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int IdTovar { get; set; }
        public string TovarName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> IdClassifications { get; set; }
    
        public virtual Classification Classification { get; set; }
    }
}
